### ISSUE TITLE
Multiple Event Handlers

### ISSUE THREAD

**Issue by guyradford** [prooph/event-sourcing#28]
I have been studying and playing with the code for a bit and cant see a way to add multiple event handlers. Each AggregateRoot contains its own Event handlers (eg whenUserWasRenamed). Part of the spec for CQRS-ES is that you can have multiple read models. I create a new AggregateRoot that had the same event listeners but the AggregateRoot failed to create and only returned null.

What am i missing?

Thank you

**Comment by prolic** [comment]
in the configuration of the event store, you need to add the event publisher plugin, like this:

```
return [
    'prooph' => [
        'event_store' => [
            'plugins' => [
                 \Prooph\EventStoreBusBridge\EventPublisher::class,
```

This will publish all domain events that happened in your aggregates to the event bus. In the event bus you can route events to event listeners (or send them to rabbitmq to handle the events async).

**Comment by prolic** [comment]
For more about this: check the documentation or visit us at https://gitter.im/prooph/improoph

**Comment by guyradford** [comment]
The docs are a little vague ;) Thank you Ill go look at https://gitter.im/prooph/improoph, I guess the google ground is dead? you still have links to it around the place.

**Comment by prolic** [comment]
we try to visit the google group from time to time, but we have a good community in the gitter chat

you can also check out our sample app at: https://github.com/prooph/proophessor-do

This will help you to get started.

**Comment by guyradford** [comment]
I totally missed proophessor-do, thank you.
