### ISSUE TITLE
Exceptions will be thrown if aggregate has no pending events

### ISSUE THREAD

**Issue by oqq** [prooph/event-sourcing#42]
> Tested with 5.0.0-beta1 Release

If I try to save a a aggregate root not having pending events with `AggregateRepository::saveAggregateRoot`, an exception is thrown by method `AggregateRepository::isFirstEvent`, since this method requires a `Message` object as first argument.

`$firstEvent` would be `null` if there is no pending event in `$domainEvents`.

```php
$firstEvent = $domainEvents[0];

if ($this->isFirstEvent($firstEvent) && $this->oneStreamPerAggregate) {
    $createStream = true;
}
```

I would prefer to throw a NoPendingEventsException, or not to do anything If there is no pending event.

Maybe an additional unit test is required for that use case.

**Comment by prolic** [comment]
wanna submit a PR?

**Comment by prolic** [comment]
btw: I would prefer no exception, just return early.

like:

```
if (empty($domainEvents)) {
    return;
}
```

**Comment by prolic** [comment]
@oqq still wanna provide a PR? otherwise I take over when I got time.

**Comment by oqq** [comment]
i am almost done.. only need to pull it. would be done today or tomorrow.
