### ISSUE TITLE
Remove ConfigurableAggregateTranslator?

### ISSUE THREAD

**Issue by codeliner** [prooph/event-sourcing#43]
Coming up prooph/event-store v7 no longer contains Aggregate related classes. They are all moved to prooph/event-sourcing. Now we have two `AggregateTranslator` implementations in one package.
Originally the `ConfigurableAggregateTranslator` was meant to be a default implementation if one don't want to use prooph/event-sourcing. 
With the new structure the `ConfigurableAggregateTranslator` is no longer needed. prooph/event-sourcing uses the decorator pattern and has its own AggregateTranslator in place.

W could create a gist of the `ConfigurableAggregateTranslator` instead and link it in the docs if one don't like the decorator approach.

**Comment by prolic** [comment]
:+1: for removing

mentioning it in the docs that this has been removed comletely is necessary. (see my docs-pr https://github.com/prooph/event-sourcing/pull/41).

creating a gist is optional I think. You can always implement the translator-interface yourself.
