### ISSUE TITLE
Snapshot args incorrect

### ISSUE THREAD

**Issue by basz** [prooph/event-sourcing#51]
```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                             
  Type error: Argument 1 passed to Prooph\SnapshotStore\Snapshot::__construct() must be of the type string, object given, called in /home-projects/api-plhw-development/deploy/relea  
  ses/20161219092409UTC/vendor/prooph/event-sourcing/src/Aggregate/SnapshotReadModel.php on line 91                                                                                   
```
https://github.com/prooph/event-sourcing/blob/develop/src/Aggregate/SnapshotReadModel.php#L86-L88

Tell me that should be `get_class($aggregateRoot)` and I'll PR it

**Comment by prolic** [comment]
$ar->toString()

Am 09.02.2017 07:46 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by basz** [comment]
? there is no toString method on the AR... Should I implement that? No... Looking at the signature of Snapshot::__construct the first argument should the the aggregateType.

```
_construct(
        string $aggregateType,
        string $aggregateId,
        $aggregateRoot,
        int $lastVersion,
        DateTimeImmutable $createdAt
    )
```

Then get_class() should do it?

**Comment by basz** [comment]
I now see the following is used elsewhere to get the AR type (vendor/prooph/snapshotter/src/StreamSnapshotProjection.php) and would prevent adding the toString method to the aggregate. I think that would be better, no?

`(string) AggregateType::fromAggregateRoot($aggregateRoot),`

**Comment by prolic** [comment]
nice hint: @codeliner what do you think?

**Comment by codeliner** [comment]
looks good :+1:

**Comment by basz** [comment]
ok, ill do a pr
