### ISSUE TITLE
Keeping up with PHP versions

### ISSUE THREAD

**Issue by amad** [prooph/event-sourcing#68]
I'm using Prooph in a project which is running on php7.0. Hence I'm locked on `prooph/event-sourcing:v4.x`.

Do you accept updates on older versions? Changes would be to upgrade `ramsey/uuid` which is being used in the `v4`.

**Comment by prolic** [comment]
We currently are no more developing the old version 4.x, we only provide bugfixes when needed. However if you would like to add an improvement yourself (including tests and doc), this would be very welcomed.
About ramsey/uuid: No! This would be a BC break and will never be upgraded without a new major release (which we already have!).
Use https://github.com/MattKetmo/uuid-2x-bridge if you need v3 in your project.
