### ISSUE TITLE
Move 'aggregateId' up

### ISSUE THREAD

**Issue by oqq** [prooph/event-sourcing#74]
The aggregateId method from EventProducerTrait and EventSourcedTrait are not related to that traits, but to the abstract AggregateRoot class which uses this traits.

So we should move this method up.

Already done in this PR: https://github.com/prooph/event-sourcing/pull/73/files
But suspended until we release the next major version

cc @prolic

**Comment by codeliner** [comment]
not sure about this change. pinging @Xerkus (author of the traits)

The method is needed by the [ClousureAggregateTranslator](https://github.com/prooph/event-sourcing/blob/master/src/EventStoreIntegration/ClosureAggregateTranslator.php#L54)

And the primary goal of the traits is that you can use them without the need to extend from AggregateRoot, hence the method must be present in the AR class using the traits ...

**Comment by Xerkus** [comment]
Here is why it is included in traits: https://github.com/prooph/event-sourcing/pull/62#discussion_r115600870

By adding it to both traits we ensure presence of `aggregateId` if AggregateRoot or one of the traits is used.

**Comment by Xerkus** [comment]
You can safely remove them and that won't be a BC break btw. Abstract methods are implemented in users code.
