### ISSUE TITLE
Missing aggregate ID

### ISSUE THREAD

**Issue by enumag** [prooph/event-sourcing#83]
We encountered an interesting error in our application today. It turned out to be our fault but I think prooph could handle such case a bit better.

What happened was basically this:

```php
final class Foo extends AggregateRoot
{
    /** @var FooId */
    private $fooId;

    /** @var BarId */
    private $barId;

	protected function aggregateId(): string
	{
		return (string) $this->barId;
	}
}
```

The bug in the code above is that `aggregateId` should return `(string) $this->fooId` instead. `$this->barId` was null so it returned an empty string.

The result was that the event was saved in the event store but `_aggregate_id` in the event metadata was an empty string.

Then database failed on this [unique check](https://github.com/prooph/pdo-event-store/blob/master/src/PersistenceStrategy/PostgresSingleStreamStrategy.php#L61-L62) when we saved a second aggregate root of the same type.

I think there should have been an exception thrown when trying to save the first aggregate root - maybe [here](https://github.com/prooph/event-sourcing/blob/master/src/Aggregate/AggregateRepository.php#L101) or in the aggregate translator? I'm not exactly sure where to put the check.

**Comment by prolic** [comment]
Don't cast to string at all. Use toString method and you will be save (at
least as long bar is null).

**Comment by enumag** [comment]
Yes, I've figured that out as well. But that's not really the point - saving an event without aggregate ID could be considered a bug in prooph.

**Comment by prolic** [comment]
We can let it generate a uuid and persist that if it's null. What do you think?

**Comment by enumag** [comment]
:-1: That would make the bug even more difficult to find. An exception should be thrown in my opinion.

**Comment by prolic** [comment]
Okay, i am fine with that. Wanna provide a PR?

**Comment by enumag** [comment]
Yeah but as I said in the first post I need an advice where the check should be done.
